---
# tasks file for containerize-py-app
- name: Copying files
  copy: 
    src: "{{item}}"
    dest: "{{app_path}}/"
  with_items: "{{app_src_list}}"

- name: Copying Dockerfile
  template:
    src:  "{{docker_file}}"
    dest: "{{app_path}}/Dockerfile"

- name: Building docker
  command: "docker build -t {{app_image_name}} ."
  args:
    chdir: "{{app_path}}"
